<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/MasterPage.master" CodeFile="ProfilePage.aspx.cs" Inherits="ProfilePage" %>

<asp:Content runat="server" ContentPlaceHolderID="contentTitle">
    <title>MyBus | Profile</title>
</asp:Content>
<asp:Content runat="server" ContentPlaceHolderID="contentMain">
    ALL BOOKINGS:<br /><br />
    <asp:GridView ID="GridView1" runat="server" OnSorting="GridView1_Sorting" AutoGenerateSelectButton="true" AllowSorting="true" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" AutoGenerateColumns="False" DataKeyNames="Id">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Booking ID" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="Source" HeaderText="Source" SortExpression="Source" />
                <asp:BoundField DataField="Destination" HeaderText="Destination" SortExpression="Destination" />
                <asp:BoundField DataField="BusOperator" HeaderText="Bus Operator" SortExpression="BusOperator" />
                <asp:BoundField DataField="ACType" HeaderText="AC Type" SortExpression="ACType" />
                <asp:BoundField DataField="SleeperType" HeaderText="Sleeper Type" SortExpression="SleeperType" />
                <asp:BoundField DataField="Arrival" HeaderText="Arrival" SortExpression="Arrival" />
                <asp:BoundField DataField="Departure" HeaderText="Departure" SortExpression="Departure" />
                <asp:BoundField DataField="Price" HeaderText="Rate (Rs)" SortExpression="Price" />
                <asp:BoundField DataField="Seats" HeaderText="Seats" SortExpression="Seats" />
            </Columns>
        </asp:GridView>
    <asp:GridView ID="GridView2" OnSorting="GridView2_Sorting" runat="server" AllowSorting="true" AutoGenerateColumns="False" DataKeyNames="Id">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Booking ID" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="RouteId" HeaderText="Route ID" SortExpression="RouteId" />
                <asp:BoundField DataField="Username" HeaderText="Username" SortExpression="Username" />
                <asp:BoundField DataField="Seats" HeaderText="Seats" SortExpression="Seats" />
            </Columns>
    </asp:GridView>
    <br />
    <br />
    <asp:GridView ID="GridView3" OnSorting="GridView3_Sorting" runat="server" AutoGenerateSelectButton="true" DataSourceID="SqlDataSource1" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" AllowSorting="true" OnSelectedIndexChanged="GridView3_SelectedIndexChanged" AutoGenerateColumns="False" DataKeyNames="Id">
        <Columns>
            <asp:BoundField DataField="Source" HeaderText="Source" SortExpression="Source" />
            <asp:BoundField DataField="Destination" HeaderText="Destination" SortExpression="Destination" />
            <asp:BoundField DataField="BusOperator" HeaderText="Bus Operator" SortExpression="BusOperator" />
            <asp:BoundField DataField="ACType" HeaderText="AC Type" SortExpression="ACType" />
            <asp:BoundField DataField="SleeperType" HeaderText="Sleeper Type" SortExpression="SleeperType" />
            <asp:BoundField DataField="Arrival" HeaderText="Arrival" SortExpression="Arrival" />
            <asp:BoundField DataField="Departure" HeaderText="Departure" SortExpression="Departure" />
            <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" />
            <asp:BoundField DataField="Seats" HeaderText="Seats" SortExpression="Seats" />   
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:MyBusConnectionString %>" 
                SelectCommand="SELECT * FROM Routes" 
                UpdateCommand="UPDATE Routes SET Source=@Source,Destination=@Destination,BusOperator=@BusOperator,ACType=@ACType,SleeperType=@SleeperType,Arrival=@Arrival,Departure=@Departure,Price=@Price,Seats=@Seats WHERE Id=@Id"
                DeleteCommand="DELETE FROM Routes WHERE Id=@Id"
                InsertCommand="INSERT INTO Routes (Source, Destination, BusOperator, ACType, SleeperType, Arrival, Departure, Price, Seats) VALUES (@Source, @Destination, @BusOperator, @ACType, @SleeperType, @Arrival, @Departure, @Price, @Seats)">

                <UpdateParameters>
                    <asp:Parameter Name="Source" />
                    <asp:Parameter Name="Destination" />
                    <asp:Parameter Name="BusOperator" />
                    <asp:Parameter Name="ACType" />
                    <asp:Parameter Name="SleeperType" />
                    <asp:Parameter Name="Arrival" />
                    <asp:Parameter Name="Departure" />
                    <asp:Parameter Name="Price" />
                    <asp:Parameter Name="Seats" />
                </UpdateParameters> 
                <DeleteParameters>
                    <asp:Parameter Name="Id"/>
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="Source" />
                    <asp:Parameter Name="Destination" />
                    <asp:Parameter Name="BusOperator" />
                    <asp:Parameter Name="ACType" />
                    <asp:Parameter Name="SleeperType" />
                    <asp:Parameter Name="Arrival" />
                    <asp:Parameter Name="Departure" />
                    <asp:Parameter Name="Price" />
                    <asp:Parameter Name="Seats" />
                </InsertParameters>
            </asp:SqlDataSource>
    <br /><br />
    <asp:Label ID="TextBox10" runat="server" Width="128px"></asp:Label>
    <asp:Label ID="TextBox1" runat="server" Width="90px" Text="Source:"></asp:Label>
    <asp:Label ID="TextBox2" runat="server" Width="90px" Text="Destination:"></asp:Label>
    &nbsp;
    <asp:Label ID="TextBox3" runat="server" Width="90px" Text="BusOperator:"></asp:Label>
    &nbsp;&nbsp;
    <asp:Label ID="TextBox4" runat="server" Width="90px" Text="ACType:"></asp:Label>
    
    <asp:Label ID="TextBox5" runat="server" Width="90px" Text="SleeperType:"></asp:Label>
    &nbsp;&nbsp;
    <asp:Label ID="TextBox6" runat="server" Width="90px" Text="Arrival:"></asp:Label>
    &nbsp;&nbsp;&nbsp;
    <asp:Label ID="TextBox7" runat="server" Width="90px" Text="Departure:"></asp:Label>
    &nbsp;&nbsp;
    <asp:Label ID="TextBox8" runat="server" Width="90px" Text="Price:"></asp:Label>
    &nbsp;&nbsp;
    <asp:Label ID="TextBox9" runat="server" Width="90px" Text="Seats:"></asp:Label>
    <br />
    <asp:Button ID="buttonInsert" Width="120px" Text="Insert" runat="server" OnClick="buttonInsert_Click" />
    <asp:TextBox ID="TextBoxSource" runat="server" Width="90px"></asp:TextBox>
    <asp:TextBox ID="TextBoxDestination" runat="server" Width="90px"></asp:TextBox>
    <asp:TextBox ID="TextBoxBusOperator" runat="server" Width="90px"></asp:TextBox>
    <asp:TextBox ID="TextBoxACType" runat="server" Width="90px"></asp:TextBox>
    <asp:TextBox ID="TextBoxSleeperType" runat="server" Width="90px"></asp:TextBox>
    <asp:TextBox ID="TextBoxArrival" runat="server" Width="90px"></asp:TextBox>
    <asp:TextBox ID="TextBoxDeparture" runat="server" Width="90px"></asp:TextBox>
    <asp:TextBox ID="TextBoxPrice" runat="server" Width="90px"></asp:TextBox>
    <asp:TextBox ID="TextBoxSeatsInsert" runat="server" Width="90px"></asp:TextBox>
    <br />
    <br />
    <asp:Label ID="labelCancel" runat="server" Text="Cancellation for booking ID: " Visible="false" /><br /><br />
    <asp:Label ID="labelTickets" runat="server" Text="How many tickets do you want to cancel: " Visible="false" /><asp:TextBox runat="server" ID="textboxSeats" Visible="false" />
    <asp:CustomValidator ID="seatsValidate" OnServerValidate="Unnamed_ServerValidate" ControlToValidate="textboxSeats" runat="server" ValidateEmptyText="true" Display="Dynamic" ForeColor="Red" ErrorMessage="Enter valid number of seats" Visible="false" />
    <asp:Button ID="buttonCancelTickets" runat="server" Text="Cancel Tickets" Visible="false" OnClick="buttonCancelTickets_Click" />&nbsp;&nbsp;&nbsp;<asp:Button ID="buttonBack" runat="server" CausesValidation="false" Visible="false" Text="Back" OnClick="buttonBack_Click" />
</asp:Content>
